version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: test-unit
    versions:
    - 3.3.9
    - 3.4.0
  - dependency-name: delayed_job_active_record
    versions:
    - 4.1.5
  - dependency-name: paperclip
    versions:
    - 4.3.7
